CREATE ROLE kbase WITH
  NOLOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION;

COMMENT ON ROLE kbase IS 'Владелец БД kbase';

CREATE ROLE kbase_user WITH
  NOLOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION;

CREATE USER kbase_admin WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION;

GRANT kbase TO kbase_admin;

COMMENT ON ROLE kbase_admin IS 'Главный в БД KBase.';

CREATE USER kbase_imak WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION;

GRANT kbase_user TO kbase_imak;

COMMENT ON ROLE kbase_imak IS 'Пользователь БД KBase';